### PR TITLE
Personal workspace

### PR DESCRIPTION
**Pull request by Ayesha-iqbal**

### CODE REVIEW

**Comment by Sashanity** [comment]
changed upload buttons using material ui

**Review by Sashanity — COMMENTED** [review]
self approve

**Comment by Sashanity** [comment]
image
image

**Comment by Sashanity** [comment]
Question what icon use for the home/search screen @Ayesha-iqbal @tienquocnguyen 
image
image

**Comment by Ayesha-iqbal** [comment]
Hi Sasha,

Thank you for making it look prettier I like both but the second home button looks good 😍

**Pull request merged**
