### PR TITLE
Editor

### PR DESCRIPTION
**Pull request by Sashanity**
Still doesn't process link

Screenshots: if bigger than an A4 page are printed "whatever fit". Possible solution is to fit to same width -> height would be adjusted automatically

To test: run "npm i" to install new node modules. Start backend. Start client. Head to personal workspace-> new note (opens editor) -> create some sample input in the editor -> hit download button. Result: downloading for pdf should be started and pdf with your sample data produced

### CODE REVIEW

**Comment by Sashanity** [comment]
Still doesn't process link

Screenshots, if bigger than an A4 page are printed "whatever fit". Possible solution is to fit to same width -> height would be adjusted automatically

**Review by tienquocnguyen — CHANGES_REQUESTED** [review]
Tested by inputting a bunch of q's. 
Observations: 5 pages of words still resulted in pdf. Newline is not accounted for (when you press enter, the empty space doesn't show up in the pdf). Spaces come out as "nbsp;" in the pdf. 

Good comments!

**Comment by Sashanity** [comment]
I think it is the downfall of the replacing function I run on the text input. The data comes with html tags, so I'm stripping it. I guess that lead to what you are describing. Gina check it out :)

**Review by Sashanity — COMMENTED** [review]
:)

**Comment by Sashanity** [comment]
> Tested by inputting a bunch of q's.
> Observations: 5 pages of words still resulted in pdf. All files were saved as "file." Newline is not accounted for (when you press enter, the empty space doesn't show up in the pdf). Spaces come out as "nbsp;" in the pdf.
> 
> Good comments!

**Review by Sashanity — COMMENTED** [review]
ready

**Review by tienquocnguyen — APPROVED** [review]
tested by printing out "this is a test" on two different blocks. The empty space appears and it looks good to me.

**Review by mcinerneym — APPROVED** [review]
Tested and it works as expected. Approved.

**Pull request merged**
