### PR TITLE
Organize files and Updated upload form

### PR DESCRIPTION
**Pull request by Ayesha-iqbal**
Please check I organized the files and updated the upload form. We will work on select box CSS in next meeting

### CODE REVIEW

**Comment by Sashanity** [comment]
@Ayesha-iqbal  TriggerButton.js is not a member of the upload form. It is used in the sidebar as well. Perhaps put it in its own directory?

**Comment by tienquocnguyen** [comment]
API key is pushed, can you delete it or include the file in gitignore Ayesha?

**Comment by Sashanity** [comment]
v_v
it is not the gitignore, I think it is in her gittree, so she keeps pushing it. 
i learned it the hard way.

**Comment by Ayesha-iqbal** [comment]
I have included in the gitignore I don't know why it keeps pushing it I can delete it and push again

**Pull request closed without merging**
